# Семейства распределений в наивном классификаторе Байеса 

Вам предлагается выяснить, какое распределение лучше использовать в наивном байесовском классификаторе в зависимости от вида признаков.

1. Загрузите датасеты [`digits`](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html) и [`breast_cancer`](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html) из `sklearn.datasets`.
2. Выведите несколько строчек из обучающих выборок и посмотрите на признаки.
3. С помощью `sklearn.cross_validation.cross_val_score` c настройками по умолчанию и вызова метода `mean()` у возвращаемого этой функцией `numpy.ndarray`, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать `BernoulliNB`, `MultinomialNB` и `GaussianNB`. Насколько полученные результаты согласуются с рекомендациями из лекций?

Два датасета, конечно, еще не повод делать далеко идущие выводы, но при желании вы можете продолжить исследование на других выборках (например, из UCI репозитория).

Для сдачи задания ответьте на приведенные ниже вопросы.

## Вопрос 1

Каким получилось максимальное качество классификации на датасете `breast_cancer`?

## Вопрос 2

Каким получилось максимальное качество классификации на датасете `digits`?

## Вопрос 3

Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):

1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли;

2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением;

3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков;

4) На вещественных признаках лучше всего сработало нормальное распределение.

In [17]:
from sklearn.datasets import load_digits, load_breast_cancer
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

In [2]:
data_digits = load_digits()
data_breast_cancer = load_breast_cancer()

In [ ]:
X_digits, y_digits = data_digits.data, data_digits.target
X_breast_cancer, y_breast_cancer = data_breast_cancer.data, data_breast_cancer.target

In [47]:
X_digits[:3]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

In [37]:
y_digits

array([0, 1, 2, ..., 8, 9, 8])

In [48]:
X_breast_cancer[:3]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [49]:
y_breast_cancer[:30]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0])

## Bernoulli

In [26]:
bnb = BernoulliNB()
bnb_digits_scores = cross_val_score(bnb, X_digits, y_digits)
bnb_digits_scores.mean()

0.8258236507780582

In [27]:
bnb_cancer_scores = cross_val_score(bnb, X_breast_cancer, y_breast_cancer)
bnb_cancer_scores.mean()

0.6274204028589994

## Multinomial

In [28]:
clf = MultinomialNB()
clf_digits_scores = cross_val_score(clf, X_digits, y_digits)
clf_digits_scores.mean()

0.8708771489735053

In [29]:
clf_cancer_scores = cross_val_score(clf, X_breast_cancer, y_breast_cancer)
clf_cancer_scores.mean()

0.8945790401930752

## Gaussian

In [30]:
gnb = GaussianNB()
gnb_digits_scores = cross_val_score(gnb, X_digits, y_digits)
gnb_digits_scores.mean()

0.8186003803550138

In [31]:
gnb_cancer_scores = cross_val_score(gnb, X_breast_cancer, y_breast_cancer)
gnb_cancer_scores.mean()

0.9367492806089297

### Results

In [44]:
def write_answer(*answers, task_number=None):
    filename = f'task{task_number}.txt' if task_number else 'task.txt'
    with open(filename, 'w') as f:
        f.write(' '.join([str(ans) for ans in answers]))

In [45]:
write_answer(gnb_cancer_scores.mean(), task_number=1)

In [46]:
write_answer(clf_digits_scores.mean(), task_number=2)

In [51]:
write_answer(*[3, 4], task_number=3)